Repository TonyKimisintheHouse/Raj-s-Jar-Files, pull requests merged in 2019-03, with the labels that each got.

#49 Make Model Singleton
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/model/Model.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/MainViewModel.java
Labels: design

#48 Add species, habitats and implement dynamic planet creation
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Player.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/PlayerBuilder.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Habitats.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Planet.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/PlanetNames.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/ResourceClassification.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Species.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Universe.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/model/Model.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/utility/LogCustom.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/PlayerTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/PlanetNamesTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/PlanetTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/SolarSystemTester.java
  doc/entity-class-doc.md
Labels: Feature, extra credit, reviewed

#53 Merge M7 to Master
  .idea/workspace.xml
  android/.idea/misc.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/game/Game.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Good.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Item.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Marketplace.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/TradeGoods.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/MarketTransactionValidator.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/TransactionOrder.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/TransactionResult.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/TransactionType.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/TransactionValidator.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Player.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Ship.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Events.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Habitats.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Planet.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/ResourceClassification.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/SolarSystem.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Species.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Universe.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/helper/ListViewItemCheckboxBaseAdapter.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/helper/ListViewItemDTO.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/helper/ListViewItemViewHolder.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/model/Model.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/GameViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/MarketViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/StartViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/GameActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/MarketActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/ShipActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/StartActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/TravelActivity.java
  android/app/src/main/res/drawable/planet.png
  android/app/src/main/res/layout/activity_game.xml
  android/app/src/main/res/layout/activity_list_view_with_checkbox.xml
  android/app/src/main/res/layout/activity_list_view_with_checkbox_item.xml
  android/app/src/main/res/layout/activity_market.xml
  android/app/src/main/res/layout/activity_ship.xml
  android/app/src/main/res/layout/activity_start.xml
  android/app/src/main/res/layout/activity_travel.xml
  android/app/src/main/res/layout/content_game.xml
  android/app/src/main/res/layout/content_main.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/MarketTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/TransactionTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/PlayerTester.java
Labels: demo

#54 Javadocs
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Good.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Item.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/Marketplace.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/TradeGoods.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/MarketTransactionValidator.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/TransactionOrder.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Player.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Ship.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Events.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Habitats.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Planet.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/PlanetNames.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/ResourceClassification.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/SolarSystem.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Species.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/helper/ListViewItemCheckboxBaseAdapter.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/helper/ListViewItemDTO.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/model/Model.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/GameViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/MarketViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/StartViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/BaseActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/GameActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/MarketActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/ShipActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/StartActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/TravelActivity.java
  android/build.gradle
Labels: reviewed

#59 Merge M8 to master
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/game/Game.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/transaction/MarketTransactionValidator.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Location.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Player.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Ship.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/Wallet.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Habitats.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/Planet.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/SolarSystem.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/model/Model.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/GameViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/ShipViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/StartViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/viewmodels/TravelViewModel.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/GameActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/MapView.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/MarketActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/ShipActivity.java
  android/app/src/main/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/views/TravelActivity.java
  android/app/src/main/res/drawable/rocket.png
  android/app/src/main/res/layout/activity_game.xml
  android/app/src/main/res/layout/activity_ship.xml
  android/app/src/main/res/layout/activity_travel.xml
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/market/TransactionTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/player/PlayerTester.java
  android/app/src/test/java/edu/gatech/cs2340/rajsjarfiles/spacetrader/entity/universe/PlanetTester.java
Labels: demo
